# ~/.dein_lazy.toml

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']


### Programming
## Lisp
[[plugins]]
repo = 'kovisoft/slimv'
on_ft = ['lisp']
hook_source = '''
  nmap <D-Enter> ,d j
  imap <D-Enter> <ESC> ,d i
  nmap <LocalLeader>rf ,c
  nmap <LocalLeader>rq ,Q
  nmap <LocalLeader>cc ,b
  nmap <LocalLeader>a ,a
  nmap <LocalLeader>n ,n
'''

## R
[[plugins]]
repo = 'jalvesaq/Nvim-R'
on_ft = ['r', 'rmd']
hook_source = '''
  let g:R_assign = 0 
  nmap <D-Enter> <Plug>RDSendLine
  imap <D-Enter> <ESC> <Plug>RDSendLine i
  nmap <LocalLeader>cc <Plug>RSendChunk
  vmap <LocalLeader>ss <Plug>RDSendSelection <C-c>
  nmap <LocalLeader>pp <Plug>RDSendParagraph
  nmap <LocalLeader>cn <Plug>RNextRChunk
  nmap <LocalLeader>cN <Plug>RPreviousRChunk

  " Insert chunk
  nnoremap <Leader>tc :Templatechunk<CR>jo
  command! Templatechunk call s:Templatechunk()
  function! s:Templatechunk()
    call append(line("."), "```{r, warning=FALSE, message=FALSE}")
    call append(line(".")+1,"```")
  endfunction
  nnoremap <Leader>tC :TemplateChunk<CR>jjo
  command! TemplateChunk call s:TemplateChunk()
  function! s:TemplateChunk()
    call append(line("."), "")
    call append(line(".")+1, "```{r, warning=FALSE, message=FALSE}")
    call append(line(".")+2,"```")
  endfunction
'''

## Tex
[[plugins]] 
repo = 'thinca/vim-quickrun'
on_ft = ['tex']
hook_add = '''
let g:quickrun_config = {
\   'tex': {
\       'command': 'latexmk',
\       'exec': ['%c -gg -pdfdvi %s']
\   },
\}
'''

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = '''
let g:vimtex_fold_envs = 0
let g:tex_indent_brace=0
'''
hook_source = '''
  " TexShopでtexファイルを表示
  nnoremap <Leader>ts :TeXShopRun<CR>
  command! TeXShopRun call s:TeXShopRun()
  function! s:TeXShopRun()
    let e = expand("%:e")
    if e == "tex"
      :!open -a /Applications/TeX/TeXShop.app %:r.tex
      echo "Open in TeXShop"
    else
      echo "File is not tex"
    endif
  endfunction

 " Insert align
  nnoremap <Leader>ta :TemplateAlign<CR>jo
  command! TemplateAlign call s:TemplateAlign()
  function! s:TemplateAlign()
    call append(line("."), "\begin{align}")
    call append(line(".")+1,"\end{align}")
  endfunction

 " Insert itemize
  nnoremap <Leader>ti :TemplateItemize<CR>jo
  command! TemplateItemize call s:TemplateItemize()
  function! s:TemplateAlign()
    call append(line("."), "\begin{itemize}")
    call append(line(".")+1,"\end{itemize}")
  endfunction
'''
