# ~/.dein_lazy.toml

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

### Programming
## Lisp
[[plugins]]
repo = 'kovisoft/slimv'
on_ft = ['lisp']
hook_source = '''
	nmap <D-Enter> ,d j
	imap <D-Enter> <ESC> ,d i
	nmap <LocalLeader>rf ,c
	nmap <LocalLeader>cc ,b
'''

## R
[[plugins]]
repo = 'jalvesaq/Nvim-R'
on_ft = ['r', 'rmd']
hook_source = '''
  let g:R_assign = 0 
	let g:R_rconsole_width = 40
	let g:R_rconsole_height = 50
	nmap <D-Enter> <Plug>RDSendLine
	imap <D-Enter> <ESC> <Plug>RDSendLine i
	nmap <LocalLeader>cc <Plug>RSendChunk
	vmap <LocalLeader>ss <Plug>RDSendSelection <C-c>
	nmap <LocalLeader>pp <Plug>RDSendParagraph
	nmap <LocalLeader>cn <Plug>RNextRChunk
	nmap <LocalLeader>cN <Plug>RPreviousRChunk
'''
