# ~/.dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

### Colorschemes
[[plugins]]
repo = 'sjl/badwolf'
hook_add = '''
function! Badwolf()
	colorscheme badwolf
	highlight Comment ctermfg=22 guifg=#4286f4
endfunction
command! Skinbwolf call Badwolf()
'''
