# ~/.dein_lazy.toml

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']


### Programming
## Lisp
[[plugins]]
repo = 'kovisoft/slimv'
on_ft = ['lisp']
hook_source = '''
  nmap <D-Enter> ,d j
  imap <D-Enter> <ESC> ,d i
  nmap <LocalLeader>rf ,c
  nmap <LocalLeader>rq ,Q
  nmap <LocalLeader>cc ,b
	nmap <LocalLeader>a ,a
	nmap <LocalLeader>n ,n
'''

## R
[[plugins]]
repo = 'jalvesaq/Nvim-R'
on_ft = ['r', 'rmd']
hook_source = '''
  let g:R_assign = 0 
  nmap <D-Enter> <Plug>RDSendLine
  imap <D-Enter> <ESC> <Plug>RDSendLine i
  nmap <LocalLeader>cc <Plug>RSendChunk
  vmap <LocalLeader>ss <Plug>RDSendSelection <C-c>
  nmap <LocalLeader>pp <Plug>RDSendParagraph
  nmap <LocalLeader>cn <Plug>RNextRChunk
  nmap <LocalLeader>cN <Plug>RPreviousRChunk
'''

## Tex
[[plugins]] 
repo = 'thinca/vim-quickrun'
on_ft = ['tex']
hook_add = '''
let g:quickrun_config = {
\   'tex': {
\       'command': 'latexmk',
\       'exec': ['%c -gg -pdfdvi %s']
\   },
\}
'''

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = '''
let g:vimtex_fold_envs = 0
let g:tex_indent_brace=0
'''
