# ~/.dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'


### Tex
[[plugins]] 
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'tex': {
\       'command': 'latexmk',
\       'exec': ['%c -gg -pdfdvi %s']
\   },
\}
'''

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
let g:vimtex_fold_envs = 0
let g:tex_indent_brace=0
let g:vimtex_view_general_viewer = 'skim'
'''

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

### Colorschemes
[[plugins]]
repo = 'sjl/badwolf'
hook_add = '''
function! Badwolf()
	colorscheme badwolf
	highlight Comment ctermfg=22 guifg=#4286f4
endfunction
command! Skinbwolf call Badwolf()
'''
